### ISSUE TITLE
LESS

### ISSUE THREAD

**Issue by evandentremont** [zurb/ink#113]
I'm in the process of converting ink to LESS, and tying bootstrap's variables.css into it. 

Not so much an issue as an RFC I guess. Any thoughts / requests?

https://github.com/evandentremont/DanceDB/tree/ink/app/views/emails/ink

**Comment by rafibomb** [comment]
@benjamin-patch Yes! It is in the works now! 

@evandentremont Even though we're going Sass, we want to add your port to the list of Resources we'll publish. http://foundation.zurb.com/develop/resources.html
