### ISSUE TITLE
Inliner Doesn't Work

### ISSUE THREAD

**Issue by Lynda333** [zurb/ink#125]
Went to use the Inliner tonight and I pasted my code and it didn't load. It was stuck on `Loading...`

Tried it in Firefox v37 and Chrome v40. Hope it is a temporary issue.

**Comment by ierpe** [comment]
+1
HTML Response : 
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.1.19</center>
</body>
</html>
```

**Comment by elidickinson** [comment]
I can't help you with Zurb's inliner, but I built my own to help test new template designs that you're free to use: http://email-inliner.industrydive.com/ the source is here https://github.com/industrydive/dive-email-inliner. [Premailer](https://github.com/peterbe/premailer) does most of the heavy lifting.

**Comment by laantorchaweb** [comment]
Same issue here, 502.

![image](https://cloud.githubusercontent.com/assets/930943/6486357/204723c2-c269-11e4-95fd-374d510743f3.png)

**Comment by esseguin** [comment]
Same issue here.

**Comment by ComanderCyber** [comment]
Alternative is this inliner from capagne monitore http://inliner.cm/ even possible. But with a little lucky works the ink inliner again as soon as possible. ;-)

**Comment by Lynda333** [comment]
I am going to close this as it appears the inliner is working fine again. Must of been a temporary issue.
