### ISSUE TITLE
How to stop hyphenation?

### ISSUE THREAD

**Issue by lspoor** [zurb/ink#143]
Title says it all really, I'm getting paragraphs and headings which are hyphenating..

**Comment by freemagee** [comment]
Look for this:

td {
  word-break: break-word;
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
  border-collapse: collapse !important;
}

in ink css

change to

td {
  word-break: break-word;
  -webkit-hyphens: none;
  -moz-hyphens: none;
  hyphens: none;
  border-collapse: collapse !important;
}

**Comment by tedw** [comment]
Those styles are in the `foundation-emails` package itself inside of `_normalize.scss`. The only way to disable them is to add more CSS overriding them. This works, but is messy. Would prefer an option to disable it.

**Comment by Luneya** [comment]
Even in 2017 the hyphenation is still in foundation-emails. 
I too have overwritten it with the following adjustments in my custom_css.scss (which is imported latest and would therefore override the classes defined in other css files):

td {
word-break: keep-all;
-moz-hyphens: none; 
-ms-hyphens: none; 
-webkit-hyphens: none; 
hyphens: none;
}

I agree it is messy and should be in the settings.scss so we are able to override it before it gets inlined.

**Comment by renatocarvalho** [comment]
The solution that @Luneya pointed works. However, it's generating a lot of extra size on the output of the HTML. Use it carefully.

**Comment by baticodes** [comment]
@Luneya solution did the trick for me

**Comment by giotannico** [comment]
Hi everyone. I wonder if a better solution is available. As renato says, this one is generating a lot of extra size on the output of the HTML.

**Comment by nikitasol** [comment]
Why not just deleting the td definitions for hyphenation from `_normalize.scss` (lines 78-84)? This way it doesn't create any additional html.

**Comment by giotannico** [comment]
I don't have access to _normalize.scss in foundation mail. Am I wrong?
app.scss is @importing 'foundation-emails' and I believe there is is the rule

**Comment by nikitasol** [comment]
`normalize.scss` is in node-modules > foundation-emails > scss > components
