### ISSUE TITLE
Why max width is 580px?

### ISSUE THREAD

**Issue by regepan** [zurb/ink#144]
Is there any reason?
Because I want to change width more wider. But I should not do it?

**Comment by rafibomb** [comment]
You can change it. 

You can see more on this here: http://foundation.zurb.com/forum/posts/35594-how-to-change-email-width-to-700px

**Comment by regepan** [comment]
Thanks. It is very helpful for me.

**Comment by buric-k** [comment]
Hi, I have a same issue like @regepan and that link is not working anymore... 
Some help would be nice.

Thank you

**Comment by DanielRuf** [comment]
@kristina001b it depends on your setup. Do you use the Sass or CSS version?

**Comment by DanielRuf** [comment]
In general the `global-width` setting can be changed.
See https://github.com/foundation/foundation-emails/blob/v2.2.1/scss/settings/_settings.scss#L30

https://stackoverflow.com/questions/42998118/how-to-change-the-global-width-in-zurb-foundation-for-emails
