### ISSUE TITLE
Examples does not work anymore in Gmail 

### ISSUE THREAD

**Issue by AlexGrs** [zurb/ink#147]
Hi guys,

I tried to use Zurb Ink to design my email template. It is working fine in Outlook but fail to render in Gmail and I have absolutely no idea why.

Even in Litmus, the rendering is not ok : 

<img width="563" alt="capture d ecran 2015-10-15 a 19 50 55" src="https://cloud.githubusercontent.com/assets/12913892/10522566/1face0c8-7376-11e5-93d0-9684a3ceedfa.png">

But, when you look at the testing on the example page, the rendering seems ok (https://litmus.com/pub/85a1b19)... Is there any chance the code is different between the example we download and the code used on Litmus ?

**Comment by akeilox** [comment]
Thats odd. Did you run the html with CSSinliner before sending?

**Comment by AlexGrs** [comment]
I just tried with the inliner and it worked... I completely missed this step... Thank you. 

My main issue here is that I use a python script to generate the email. Is there any inliner compatible with Zurb Ink in python ?

**Comment by elidickinson** [comment]
Take a look at https://github.com/peterbe/premailer

**Comment by akeilox** [comment]
I was looking for Premailer that works in C# for the INK, but somehow Premailer.NET here on github doesnt seem to work (breaks the sidebar example for instance). Anyone using C# with INK out there?

I did read the INK cssinliner is using https://github.com/zurb/premailer so you might get better luck with phython.

**Comment by elidickinson** [comment]
I would recommend https://github.com/peterbe/premailer over https://github.com/zurb/premailer for python. I've been using it in production for some time and it is very solid and actively maintained. The other one has a last commit of 2013.

**Comment by AlexGrs** [comment]
Thank you ! I'll give it a try :)
