### ISSUE TITLE
Android responisiveness

### ISSUE THREAD

**Issue by avoliva** [zurb/ink#152]
Having issues with the responsiveness in Android Gmail App. It used to work, but now I'm having issues. What I mean is when using the Grid layout, I have two images set next to each other. On iPhone and other mobile devices, the images stack, however on Android they still remain side to side

Example:

How it looks on Android
![screen shot 2016-01-07 at 12 29 00 pm](https://cloud.githubusercontent.com/assets/2057701/12182012/77a496f8-b53a-11e5-9ddd-04d2e3341ff4.png)

iPhone:
![screen shot 2016-01-07 at 12 31 00 pm](https://cloud.githubusercontent.com/assets/2057701/12182033/947f34b8-b53a-11e5-9dda-a3a41677e01c.png)

I'm positive this used to work in Android, though it seems something has changed. Is this an update on Android's part or on Zurb's?

**Comment by tazzydemon** [comment]
Foundation for emails 1.x and now 2.x have never worked responsively for me in the Gmail app. I'm not aware that I am doing anything wrong... correct inlining, testing using pasted html using services like Putsmail and so on. Every other mail client seems fine. It has me stumped if others have this working.

**Comment by avoliva** [comment]
My issue is I was using the grid layout instead of the block-grid layout. If you go the docs [here](http://foundation.zurb.com/emails/docs.html) and go to the compatibility section you'll find that only block-grid works with gmail

**Comment by tazzydemon** [comment]
I am somewhat ashamed to say that I only read that afterwards. However it does not change the fact that v2.x is the same and gmail is simply ubiquitous. The system I reference and have used does not suffer from this problem.
